import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {createHash,createHmac} from 'node:crypto';
const script=await readFile(new URL('../integrations/google-apps-script/Code.gs',import.meta.url),'utf8');
function setup(){
  const files=[],folders=[],rows=[];let writes=0;
  const list=a=>{let i=0;return {hasNext:()=>i<a.length,next:()=>a[i++]};};
  class Folder{constructor(name){this.name=name;this.children=[];this.files=[];folders.push(this);}getSharingAccess(){return 'PRIVATE';}getFoldersByName(n){return list(this.children.filter(x=>x.name===n));}createFolder(n){writes++;const f=new Folder(n);this.children.push(f);return f;}getFilesByName(n){return list(this.files.filter(x=>x.name===n));}createFile(name,body,mime){writes++;if(typeof name==='object')({name,body,mime}=name);const f={name,body,mime,getBlob:()=>({getDataAsString:()=>body})};this.files.push(f);files.push(f);return f;}getUrl(){return 'https://drive.google.com/folders/mock';}}
  const root=new Folder('home'),props=new Map([['INTAKE_SECRET','test-secret'],['HOME_FOLDER_ID','home'],['JOB_WORKBOOK_ID','jobs'],['COST_WORKBOOK_ID','cost']]),cache=new Map();
  const sheet={getLastRow:()=>rows.length,appendRow:a=>{rows.push(a);},getRange:()=>({createTextFinder:id=>({matchEntireCell:()=>({findNext:()=>rows.find(r=>r[0]===id)||null})})})};
  const ctx=vm.createContext({Date,JSON,Number,String,Error,Math,PropertiesService:{getScriptProperties:()=>({getProperty:k=>props.get(k),setProperty:(k,v)=>props.set(k,v)})},LockService:{getScriptLock:()=>({tryLock:()=>true,hasLock:()=>true,releaseLock(){}})},CacheService:{getScriptCache:()=>({get:k=>cache.get(k),put:(k,v)=>cache.set(k,v)})},DriveApp:{Access:{PRIVATE:'PRIVATE'},getFolderById:()=>root},SpreadsheetApp:{openById:()=>({getSheetByName:()=>sheet})},ContentService:{MimeType:{JSON:'application/json'},createTextOutput:s=>({setMimeType:()=>JSON.parse(s)})},Utilities:{DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(_,v)=>[...createHash('sha256').update(typeof v==='string'?v:Buffer.from(v)).digest()],computeHmacSha256Signature:(v,k)=>[...createHmac('sha256',k).update(v).digest()],base64Decode:s=>[...Buffer.from(s,'base64')],newBlob:(v,mime,name)=>({name,mime,body:Buffer.from(v)}),formatDate:()=>new Date().toISOString().slice(0,10)}});
  vm.runInContext(script,ctx);return {ctx,files,folders,rows,props,writes:()=>writes};
}
const packet={submissionId:'12345678-abcd-1234-abcd-123456789012',project:{business:'QA',email:'qa@example.com',name:'=not a formula',project:'Label',quantity:500,versions:1,material:'White',finish:'Matte',deadline:'',notes:'Fixture only',artworkHelp:false},artwork:{file:{type:'PNG',name:'sample.png',sha256:createHash('sha256').update('test').digest('hex')},checks:[]},estimateInputs:{quantity:500}};
function request(p=packet){const timestamp=Date.now(),payload=JSON.stringify({packet:p,file:Buffer.from('test').toString('base64'),rateKey:'a'.repeat(64)});return {postData:{contents:JSON.stringify({timestamp,payload,signature:createHmac('sha256','test-secret').update(timestamp+'\n'+payload).digest('hex')})}};}
test('Drive adapter creates context and HOLD queue, then reuses receipt on retry',()=>{const s=setup();assert.equal(s.ctx.doPost(request()).ok,true);assert.ok(s.files.some(f=>f.name==='sample.png'));assert.ok(s.files.some(f=>f.name==='cost-inputs.json'));assert.equal(s.rows.length,2);assert.equal(s.rows[1][11],'HOLD');assert.equal(s.rows[1][3],"'=not a formula");const writes=s.writes();assert.equal(s.ctx.doPost(request()).ok,true);assert.equal(s.writes(),writes);assert.equal(s.rows.length,2);});
test('Drive adapter rejects bad signatures without mutations',()=>{const s=setup(),r=request(),e=JSON.parse(r.postData.contents);e.signature='0'.repeat(64);r.postData.contents=JSON.stringify(e);assert.equal(s.ctx.doPost(r).ok,false);assert.equal(s.writes(),0);});
test('Drive adapter refuses a changed retry and a mismatched file digest',()=>{const s=setup();assert.equal(s.ctx.doPost(request()).ok,true);assert.equal(s.ctx.doPost(request({...packet,project:{...packet.project,quantity:1000}})).ok,false);assert.equal(s.rows.length,2);const bad={...packet,artwork:{file:{...packet.artwork.file,sha256:'0'.repeat(64)}}};assert.equal(setup().ctx.doPost(request(bad)).ok,false);});
test('Drive daily quota blocks project creation before uploads',()=>{const s=setup();s.props.set('DAILY_LIMIT','0');assert.equal(s.ctx.doPost(request()).ok,false);assert.equal(s.files.length,0);assert.equal(s.folders.length,2);});
