import {LIMITS,sniff,parseRaster,targetFrom,rasterChecks,outcome} from './core.mjs';
import {INTAKE_LIMIT,projectPacket} from './intake.mjs';
const $=id=>document.getElementById(id);
let report=null,artwork=null,revision=0,available=false,sending=false,submitted=false,submissionId=crypto.randomUUID(),targetKey='';
const target=()=>{const c=window.PWBuilder.read(),e=window.PWBuilder.validate(c);if(e)throw Error(e);return {...targetFrom(c),measured:c.measured,stockPreview:c.stock,safeInset:c.safe,overlap:c.overlap};};
const save=(name,body,type)=>{const u=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
function syncIntake(){
  $('intake-submit').disabled=!available||!report||!artwork||artwork.size>INTAKE_LIMIT||!$('intake-consent').checked||sending||submitted;
  $('intake-readiness').textContent=!report?'Check an artwork file first to attach its results to your project.':artwork.size>INTAKE_LIMIT?'Your check report can be saved. Online project submissions currently accept files up to 3 MB; request a larger-file handoff from PRESSWRK.':`Attached: ${report.file.name} · ${report.outcome}. Files needing changes can be submitted for help.`;
}
function reset(message='File removed. Choose another artwork file.'){
  revision++;report=null;artwork=null;submitted=false;submissionId=crypto.randomUUID();$('artwork-file').value='';$('artwork-summary').hidden=true;$('artwork-empty').hidden=false;$('artwork-preview').hidden=true;$('artwork-preview').replaceChildren();$('artwork-status').textContent=message;$('intake-status').textContent='';syncIntake();
}
function syncTarget(){let t;try{t=target();$('artwork-target').textContent=`${t.name} · ${t.width} × ${t.height} in. finished · ${t.canvasWidth} × ${t.canvasHeight} in. with bleed`;}catch(e){$('artwork-target').textContent='Correct the template dimensions above before checking artwork.';}
  const k=JSON.stringify(t);if(targetKey&&k!==targetKey)reset('Template changed. Add your artwork again to check it at the new size.');targetKey=k;
}
function showResults(){
  $('artwork-status').textContent='Check complete. Review each result below.';$('artwork-verdict').textContent=report.outcome;$('artwork-filename').textContent=report.file.name;$('artwork-checks').replaceChildren();
  for(const c of report.checks){const li=document.createElement('li');li.className=c.status;const icon=document.createElement('span');icon.className='check-icon';icon.textContent=c.status==='pass'?'✓':c.status==='fail'?'×':'!';icon.setAttribute('aria-hidden','true');const body=document.createElement('div'),b=document.createElement('b');b.textContent=`${c.label} · ${c.status==='pass'?'Pass':c.status==='fail'?'Fix':'Review'}`;body.append(b);for(const [content,cls] of [[c.detail,''],[c.action,'action']])if(content){const p=document.createElement('p');p.textContent=content;p.className=cls;body.append(p);}li.append(icon,body);$('artwork-checks').append(li);}
  $('artwork-summary').hidden=false;$('artwork-empty').hidden=true;$('artwork-verdict').focus({preventScroll:true});syncIntake();
}
async function analyze(file){
  reset('Reading artwork on your device…');const token=revision;
  let timer;try{
    const t=target();if(!file||!file.size)throw Error('Choose a non-empty artwork file.');if(file.size>LIMITS.bytes)throw Error('Choose a file of 25 MB or less.');
    const bytes=new Uint8Array(await file.arrayBuffer());const type=sniff(bytes),canvas=document.createElement('canvas');canvas.setAttribute('aria-label','Artwork preview; colors are a screen approximation');
    let result;
    const run=async()=>{if(type==='PDF'){const {inspectPDF}=await import('./pdf.mjs');return inspectPDF(bytes,t,canvas);}
      const meta=parseRaster(bytes),bitmap=await createImageBitmap(file);canvas.width=Math.min(640,meta.width);canvas.height=Math.max(1,Math.round(meta.height*canvas.width/meta.width));if(canvas.height>1200){canvas.width=Math.max(1,Math.round(canvas.width*1200/canvas.height));canvas.height=1200;}canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return {...rasterChecks(meta,t),...meta};};
    result=await Promise.race([run(),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('This file is taking too long to inspect. Export a simpler print PDF or smaller image.')),45000);})]);
    const sha256=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');
    if(token!==revision)return;report={version:1,checkedAt:new Date().toISOString(),file:{name:file.name,size:file.size,type,sha256},target:t,...result,outcome:outcome(result.checks),scope:'Automated first check only. Human prepress and proof approval remain required.'};artwork=file;
    const caption=document.createElement('p');caption.textContent=type==='PDF'?'Page 1 preview · screen colors are not a print proof.':'Screen preview · color and substrate may differ in print.';$('artwork-preview').replaceChildren(canvas,caption);$('artwork-preview').hidden=false;showResults();
  }catch(e){if(token===revision){$('artwork-status').textContent=e.message||'This file could not be checked. Export a fresh PDF, JPG or PNG.';syncIntake();}}
  finally{clearTimeout(timer);}
}
$('artwork-file').addEventListener('change',e=>{if(e.target.files.length)analyze(e.target.files[0]);});
const drop=$('artwork-drop');for(const type of ['dragover','dragenter'])drop.addEventListener(type,e=>{e.preventDefault();drop.classList.add('dragging');});drop.addEventListener('dragleave',()=>drop.classList.remove('dragging'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('dragging');if(e.dataTransfer.files.length!==1){reset('Choose one artwork file at a time.');return;}analyze(e.dataTransfer.files[0]);});
$('artwork-clear').onclick=()=>reset();
$('artwork-demo').onclick=async()=>{try{const example=$('artwork-example').value;if(['cmyk-300.jpg','vector.pdf','low-image.pdf'].includes(example)){const response=await fetch('/examples/'+example);if(!response.ok)throw Error('Sample artwork could not be loaded.');await analyze(new File([await response.blob()],'sample-'+example,{type:example.endsWith('.pdf')?'application/pdf':'image/jpeg'}));return;}const t=target();const c=document.createElement('canvas');c.width=Math.ceil(t.canvasWidth*300);c.height=Math.ceil(t.canvasHeight*300);if(c.width*c.height>LIMITS.pixels)throw Error('Choose a smaller template to try the sample.');const x=c.getContext('2d');x.fillStyle='#e9e4d9';x.fillRect(0,0,c.width,c.height);x.fillStyle='#171719';x.textAlign='center';x.font=`900 ${Math.max(14,Math.min(c.width/9,c.height/5))}px Arial`;x.fillText('PRESSWRK.',c.width/2,c.height*.48);x.fillStyle='#cf2c39';x.font=`${Math.max(10,Math.min(c.width/22,c.height/12))}px Arial`;x.fillText('SAMPLE / RGB / 300 PPI',c.width/2,c.height*.65);const blob=await new Promise(r=>c.toBlob(r,'image/png'));await analyze(new File([blob],'sample-rgb-label.png',{type:'image/png'}));}catch(e){$('artwork-status').textContent=e.message;}};
$('artwork-report').onclick=()=>{if(report)save('PRESSWRK-artwork-check.txt',`PRESSWRK. ARTWORK CHECK\n${report.outcome}\n${report.file.name}\nChecked: ${report.checkedAt}\nSHA-256: ${report.file.sha256}\n\n${report.target.width} x ${report.target.height} in. finished; ${report.target.bleed} in. bleed per side.\n\n`+report.checks.map(c=>`${c.status.toUpperCase()} — ${c.label}\n${c.detail}\n${c.action}`).join('\n\n')+'\n\n'+report.scope,'text/plain');};
const form=$('intake-form');
function packet(){if(!report)throw Error('Check your artwork first.');if(!form.reportValidity())throw Error('Complete the required project details.');const p=Object.fromEntries(new FormData(form));p.artworkHelp=form.elements.artworkHelp.checked;return projectPacket(p,report,submissionId);}
$('intake-download').onclick=()=>{try{const p=packet();save('PRESSWRK-project-brief.json',JSON.stringify(p,null,2),'application/json');$('intake-status').textContent='Project brief saved to your device. It includes contact details and check results; keep it with the original artwork. Nothing has been submitted.';}catch(e){$('intake-status').textContent=e.message;}};
$('intake-consent').addEventListener('change',syncIntake);
form.addEventListener('input',()=>{submitted=false;submissionId=crypto.randomUUID();syncIntake();});
form.addEventListener('submit',async e=>{e.preventDefault();if(sending||submitted)return;try{const p=packet();if(!available)throw Error('Online submissions are not connected yet. Download your project brief to keep the details together.');if(!$('intake-consent').checked)throw Error('Confirm you agree to send this artwork and project details.');if(artwork.size>INTAKE_LIMIT)throw Error('Online submissions accept files up to 3 MB.');sending=true;syncIntake();$('intake-status').textContent='Sending the project to PRESSWRK…';const selected=artwork;const bytes=new Uint8Array(await selected.arrayBuffer());let b64='';for(let i=0;i<bytes.length;i+=8192)b64+=String.fromCharCode(...bytes.subarray(i,i+8192));const response=await fetch('/api/intake',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({packet:p,file:btoa(b64),consent:true})});const result=await response.json();if(!response.ok||!result.ok)throw Error(result.error||'We could not confirm receipt. Retry using the same submission ID.');submitted=p.submissionId===submissionId;$('intake-status').textContent=(submitted?'':'An earlier version of this form was received. Current edits have not been sent. ')+`Received. Reference: ${result.reference}. PRESSWRK will review the artwork and prepare the estimate. Production is on hold until approval.`;}catch(e){$('intake-status').textContent=e.message;}finally{sending=false;syncIntake();}});
window.addEventListener('pw:config',syncTarget);syncTarget();syncIntake();
fetch('/api/intake').then(r=>r.ok?r.json():null).then(data=>{available=data?.enabled===true;$('intake-connection').textContent=available?'Project submissions are connected. Submit to save your artwork and brief privately with PRESSWRK.':'Online submissions are being connected. You can check artwork and download a complete project brief now; nothing is sent to PRESSWRK yet.';syncIntake();}).catch(()=>{$('intake-connection').textContent='Online submissions are unavailable. You can still check artwork and save a project brief on your device.';});
